// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameProgress.Codegen
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Enemies : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Enemies GetRootAsEnemies(ByteBuffer _bb) { return GetRootAsEnemies(_bb, new Enemies()); }
  public static Enemies GetRootAsEnemies(ByteBuffer _bb, Enemies obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Enemies __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameProgress.Codegen.Weapons? Human { get { int o = __p.__offset(4); return o != 0 ? (GameProgress.Codegen.Weapons?)(new GameProgress.Codegen.Weapons()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public GameProgress.Codegen.Weapons? Titan { get { int o = __p.__offset(6); return o != 0 ? (GameProgress.Codegen.Weapons?)(new GameProgress.Codegen.Weapons()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public GameProgress.Codegen.Weapons? Shifter { get { int o = __p.__offset(8); return o != 0 ? (GameProgress.Codegen.Weapons?)(new GameProgress.Codegen.Weapons()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public GameProgress.Codegen.Weapons? Other { get { int o = __p.__offset(10); return o != 0 ? (GameProgress.Codegen.Weapons?)(new GameProgress.Codegen.Weapons()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<GameProgress.Codegen.Enemies> CreateEnemies(FlatBufferBuilder builder,
      Offset<GameProgress.Codegen.Weapons> humanOffset = default(Offset<GameProgress.Codegen.Weapons>),
      Offset<GameProgress.Codegen.Weapons> titanOffset = default(Offset<GameProgress.Codegen.Weapons>),
      Offset<GameProgress.Codegen.Weapons> shifterOffset = default(Offset<GameProgress.Codegen.Weapons>),
      Offset<GameProgress.Codegen.Weapons> otherOffset = default(Offset<GameProgress.Codegen.Weapons>)) {
    builder.StartTable(4);
    Enemies.AddOther(builder, otherOffset);
    Enemies.AddShifter(builder, shifterOffset);
    Enemies.AddTitan(builder, titanOffset);
    Enemies.AddHuman(builder, humanOffset);
    return Enemies.EndEnemies(builder);
  }

  public static void StartEnemies(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddHuman(FlatBufferBuilder builder, Offset<GameProgress.Codegen.Weapons> humanOffset) { builder.AddOffset(0, humanOffset.Value, 0); }
  public static void AddTitan(FlatBufferBuilder builder, Offset<GameProgress.Codegen.Weapons> titanOffset) { builder.AddOffset(1, titanOffset.Value, 0); }
  public static void AddShifter(FlatBufferBuilder builder, Offset<GameProgress.Codegen.Weapons> shifterOffset) { builder.AddOffset(2, shifterOffset.Value, 0); }
  public static void AddOther(FlatBufferBuilder builder, Offset<GameProgress.Codegen.Weapons> otherOffset) { builder.AddOffset(3, otherOffset.Value, 0); }
  public static Offset<GameProgress.Codegen.Enemies> EndEnemies(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameProgress.Codegen.Enemies>(o);
  }
  public EnemiesT UnPack() {
    var _o = new EnemiesT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnemiesT _o) {
    _o.Human = this.Human.HasValue ? this.Human.Value.UnPack() : null;
    _o.Titan = this.Titan.HasValue ? this.Titan.Value.UnPack() : null;
    _o.Shifter = this.Shifter.HasValue ? this.Shifter.Value.UnPack() : null;
    _o.Other = this.Other.HasValue ? this.Other.Value.UnPack() : null;
  }
  public static Offset<GameProgress.Codegen.Enemies> Pack(FlatBufferBuilder builder, EnemiesT _o) {
    if (_o == null) return default(Offset<GameProgress.Codegen.Enemies>);
    var _human = _o.Human == null ? default(Offset<GameProgress.Codegen.Weapons>) : GameProgress.Codegen.Weapons.Pack(builder, _o.Human);
    var _titan = _o.Titan == null ? default(Offset<GameProgress.Codegen.Weapons>) : GameProgress.Codegen.Weapons.Pack(builder, _o.Titan);
    var _shifter = _o.Shifter == null ? default(Offset<GameProgress.Codegen.Weapons>) : GameProgress.Codegen.Weapons.Pack(builder, _o.Shifter);
    var _other = _o.Other == null ? default(Offset<GameProgress.Codegen.Weapons>) : GameProgress.Codegen.Weapons.Pack(builder, _o.Other);
    return CreateEnemies(
      builder,
      _human,
      _titan,
      _shifter,
      _other);
  }
}

public class EnemiesT
{
  public GameProgress.Codegen.WeaponsT Human { get; set; }
  public GameProgress.Codegen.WeaponsT Titan { get; set; }
  public GameProgress.Codegen.WeaponsT Shifter { get; set; }
  public GameProgress.Codegen.WeaponsT Other { get; set; }

  public EnemiesT() {
    this.Human = null;
    this.Titan = null;
    this.Shifter = null;
    this.Other = null;
  }
}


static public class EnemiesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Human*/, GameProgress.Codegen.WeaponsVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*Titan*/, GameProgress.Codegen.WeaponsVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Shifter*/, GameProgress.Codegen.WeaponsVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 10 /*Other*/, GameProgress.Codegen.WeaponsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
